### ISSUE TITLE
Datasets

### ISSUE THREAD

**Issue by YikiSu** [UBC-MDS/dsci_532_group_04#2]
Please find the datasets that are of your interest (max to 3 datasets per person) and then let's meet again on Jan 12th, 2021 at 4pm Vancouver time. 

Please put the links and brief description of your datasets below.

**Comment by jiajie0225** [comment]
Data links:

- Spotify Data (12 numerical columns, 4 categorical columns)
   - https://www.kaggle.com/yamaerenay/spotify-dataset-19212020-160k-tracks?select=data_by_artist.csv
- Real Estate Dataset (506 rows)
   - https://www.kaggle.com/arslanali4343/real-estate-dataset

**Comment by debanandasarkar** [comment]
Datasets:

- Covid 19 datasets
    - https://opencovid.ca/api/
    - https://github.com/ishaberry/Covid19Canada
- Wine dataset
    - https://www.kaggle.com/zynicide/wine-reviews/data
- Movies
    - https://www.kaggle.com/shivamb/netflix-shows

**Comment by YikiSu** [comment]
Yiki Su is inviting you to a scheduled Zoom meeting.

Topic: Yiki Su's Zoom Meeting
Time: Jan 12, 2021 04:00 PM Pacific Time (US and Canada)

Join Zoom Meeting
https://ubc.zoom.us/j/63448360213?pwd=a0EreEFnbkhOMXlkbXp1S1dQSERJQT09

Meeting ID: 634 4836 0213
Passcode: 711187

One tap mobile
+17789072071,,63448360213#,,,,,,0#,,711187#

Dial by your location
+1 778 907 2071 (Vancouver)
+1 647 374 4685 (Toronto)
+1 647 375 2970 (Toronto)
+1 647 375 2971 (Toronto)
+1 204 272 7920 (Manitoba)
+1 438 809 7799 (Montreal)
+1 587 328 1099 (Alberta)
+1 613 209 3054 (Ottawa)

Meeting ID: 634 4836 0213
Passcode: 711187

Join by SIP
63448360213@zmca.us

Join by H.323
69.174.57.160 (Canada)
Meeting ID: 634 4836 0213
Passcode: 711187

**Comment by YikiSu** [comment]
Mental health info:
https://www.kaggle.com/osmi/mental-health-in-tech-survey (27 columns)

Life expectancy info:
https://www.kaggle.com/kumarajarshi/life-expectancy-who (22 columns)

**Comment by JuntingHe** [comment]
Dataset Link:

- https://www.kaggle.com/datasnaek/youtube-new?select=USvideos.csv (Trending YouTube Video Statistics in US region)

- https://github.com/OxCGRT/covid-policy-tracker (The Oxford Covid-19 Government Response Tracker (OxCGRT) collects systematic information on which governments have taken which measures, and when.)

- https://github.com/YouGov-Data/covid-19-tracker (Imperial College London YouGov Covid 19 Behaviour Tracker Data Hub)

**Comment by YikiSu** [comment]
https://www.kaggle.com/kumarajarshi/life-expectancy-who wins. Let's work on this one

**Comment by YikiSu** [comment]
Target audience: public communication
who we are: data analyst team
Create a dashboard for the audiences to explore different factors that affect life expectancy.
