### ISSUE TITLE
Milestone 1 Feedback

### ISSUE THREAD

**Issue by ghost** [UBC-MDS/dsci_532_group_04#25]
Hey Group 4.

Congrats on wrapping up milestone 1! You're off to a strong start. Overall, your proposal was well written. The purpose and data were both clearly presented and should provide an excellent base for you to build on. Your description of a usage scenario did well in outlining the broad reasons for using your dashboard and provided a sufficiently detailed list of it's functionality; however, I would have liked to see these two things tied together more clearly. Also, be careful with the run on sentences.

As for your dashboard itself:
- The layout and colour scheme already seem quite nice and I appreciate the fact that the map serves almost as an additional legend (tooltips with country names could add even further to this)
- I like the idea of a collapsable menu to make more effective use of space, good idea!
- The global controls seem as though they would not be relevant for all of your plots. I'd consider more carefully what is most relevant as a global control and how it will apply to each plot. It's ok to break these up into local controls too
- The bottom left plot provides an overwhelming amount of info, particularly given a public audience, and would probably be better off without the size component and possibly without the color dropdown
- The status plot seems a bit out of place with the rest of the plots. Perhaps you could have a toggle between Continent and Status instead

**Comment by debanandasarkar** [comment]
Hi @gubbelcn ,

Thanks for the feedback. Please see our actions/ comments below:

- **(Pending):** We are planning to enhance our functionality section in milestone 4, to provide more details about how our dashboard relates to usage scenario
- **(Completed):** Based on your feedback from lab session, we have modified our global filter section to have year as the only global filter and all the other filters are local to each plot element.
- **(Completed):**We modified the multi-dimensional analysis plot (bottom left), to remove the size filter. However, have retained the color axis dropdown as it only allows us to color based on continent and status, which are two of our primary dimensions for analysis.
- **(Completed):** The trend by status and trend by continent plot has been combined and users can toggle between a pair of radio button to see the desired chart.

We are keeping this issue open for now, and we will close it once we take care of the pending item.

Cheers.

**Comment by debanandasarkar** [comment]
Added a paragraph in proposal about how the dashboard functionality is related to usage scenario
